name: Coverage Report

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.7'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate coverage report
        run: |
          coverage run --source=./ -m unittest discover -p "*_test.py"
          coverage xml

      - name: Upload coverage to code climate
        env:
          CODECLIMATE_REPO_TOKEN: 6a05c74a31293c36fb325185cc5a6ceb680e94a002c4015bb3413609e65a36f1
        run: |
          codeclimate-test-reporter